### ISSUE TITLE
Checklist for v5.1

### ISSUE THREAD

**Issue by lulen11** [aimementoring/website#129]
## First priority before launch
 
**Home page first banner - @mischacolley** 
- [x] hide (TODAY) in banner title
- [x] Change APPLY NOW to (Learn more)
- [x] overlay on banner to show nav more (and on individual stories https://beta.aimementoring.com/story/the-imagination-declaration) 

**Home page second panel - @mischacolley**
- [x] Home page Second panel copy update:
- [x] Remove text on video overlay

**/be-a-mentor page @mischacolley**
- [x] review copy and update (Mischa)

**/about page @mischacolley**
- [ ] Review copy & update (Mischa)

**Mailchimp & Raisely**
- [x] Mailchimp - Update logo and button colours @mischacolley 
- [x] Raisley - Update logo and button colours @mischacolley 
- [x] Raisley - Update copy “Donate to AIME Australian Indigenous Program” to “Donate to AIME Mentoring” @mischacolley 

## Second priority would be nice to have in launch

**For Kevin**
- [ ] Could you please change the newsletter subscription form submit action to load a thank you message on the page, rather than redirect to the mailchimp page. 

**Remove scratch & update titles - @lulen11**
- [x] https://beta.aimementoring.com/positions _(to do this faster, do this in it's own PR before doing others)_
- [x] https://beta.aimementoring.com/jack-manning-bancroft
- [x] https://beta.aimementoring.com/impact
- [ ] https://beta.aimementoring.com/ambassadors
- [ ] https://beta.aimementoring.com/reports

**About pages** 
- [ ] /about page update images - @lulen11 

**Home page**
- [ ] fix ambassador svg on safari

**Know AIME page** @lulen11 
- [x] Fix up text styles
- [x] Remove scratch & update titles
- [ ] Fix btn styles
- [x] Remove FAQs

**[Book](https://beta.aimementoring.com/the-mentor) page** @lulen11 
- [ ] Fix title letter-spacing
- [ ] Grab a copy - open in a new tab

**Positions page**
- [x] Change title to AIME Positions
- [x] Remove We ranked 12th best place to work in Asia for 2016. Check below to find out why.
- [x] Change banner background
- [x] Remove salary guide and experience like no other. Just leave cogs and list of positions

**Stories page**
- [ ] Give KT and Irmin clear image guidelines 
- [ ] Update title styles

**Individual Stories page** 
- [ ] Update all `<p>` elements to be Blueprint `<Paragraph>` components in `blogPostArticle`
- [ ] Fix button componetnt at end of page

**Reports page**
- [ ] Update components to be the same as Stories (Carolina) 
- [ ] Move reports from Craft to Contentful (Rory)

**Footer** @lulen11 
- [ ] remove text-decoration on links
- [ ] Fix padding on newletter component

## Third priority after launch

- [ ] On shop.aimementoring.com - Change page template depending on what product type. Ie. on https://shop.aimementoring.com/products/the-mentor so doesn’t show ‘Fit Details’ (Carolina)
