### ISSUE TITLE
Post launch checklist

### ISSUE THREAD

**Issue by lulen11** [aimementoring/website#134]
## Right Away
- [x] Ensure robotos.txt isn't blocking production like it was on v5 & beta. Essentially remove it. @bronz3beard @camposcristianeze 
- [x] Google tag manager - check it’s on there

## Later
- [ ] Update FAQs https://github.com/aimementoring/website/issues/103
