### ISSUE TITLE
Final checklist of tasks to do by 12pm AEST Friday 14 Feb

### ISSUE THREAD

**Issue by lulen11** [aimementoring/website#204]
### **In (rough) order of highest priority**
- [x] Get scrollto functioning - https://github.com/aimementoring/website/pull/201
  - [x] Once functioning link the right anchor points - https://github.com/aimementoring/website/issues/200
- [ ] Remainder of JMB requests in https://github.com/aimementoring/website/issues/199
  - [ ] Replace /founder banner with image of jack and puppet (asked Xave to supply)
  - [ ] Add in Rhian to people (find photo)
- [x] Remove 404 redirect on Positions (if form is working on v5 now)
  - [ ] Make video and copy edits as listed in https://github.com/aimementoring/website/issues/199
**Remainder of tasks in Backlog:**
- [x] Update Impact page - https://github.com/aimementoring/website/issues/189
- [x] Raisely logo https://github.com/aimementoring/website/issues/186
- [ ] Update shop 

**Review & Merge:**
- [x] Copy updates: https://github.com/aimementoring/website/pull/202

**Chase Scotty up for**:
  - [x] Hoodie illustration
  - [ ] About page map
---
**If we get time:**
- [ ] Create 50 Word Quick News - https://github.com/aimementoring/website/pull/203
