### ISSUE TITLE
Discuss: Contentful modeling

### ISSUE THREAD

**Issue by mischacolley** [aimementoring/website#279]
Apologies this brain dump is so long. I recorded this while I was looking at #263 

> @charliemckenzie got me thinking about taxonomies in general. i.e. Categories v Tags v Content Type (as we've used it in Posts) and then I recorded this loom ...

https://www.loom.com/share/9f61e13a3b90429eb94919e5d213b124

---

**So I've got a fair bit of experience modelling content in CMSs and balancing the:**

- Editor experience
- Developer experience
- Designer experience  

**AND** 

What we are trying to do here with AIME is HARD!

**I think it's important that we acknowledge a few things:**

- We are moving very quickly 
- Content modelling is a full-time job as is editing and publishing and we don't have anyone dedicated to it
- We are going to get things wrong, we are going to over engineer things etc etc and we'll be forced to refactor. Limiting the amount is all that we can control :) 

**TODO:**

- [ ] Discuss some of the stuff here async and then if needed plan a workshop
- [x] Re #263 where do categories go beyond `Sunday Kindness` and `IN{TV}`? i.e. What are examples of other Categories we are likely to have? 
- [ ] How might these categories work with Tags? // i.e. an example from my loom was @charliemckenzie mentioning further tagging `IN{TV}` articles by the day `Youngsters`, `Artists` etc
- [ ] Consider how we are using [Content Type](https://www.dropbox.com/s/cv6g3u628dgghap/Screenshot%202020-03-27%2016.26.17.png?dl=0) [& Content Tag](https://www.dropbox.com/s/cv6g3u628dgghap/Screenshot%202020-03-27%2016.26.17.png?dl=0) as related to how we would use Category or Tags. I feel like this is very connected with [early planing here](https://docs.google.com/document/d/1xPBxvnMpnS8xsH_YxtzVCCjwP5CqaMKBr5l740FsH1Y/edit) and maybe we can do this more efficiently. For example it feels like the Editor experience and the Design would be very influenced by these where as Categories/Tags contribute to the UX 🤔 
 
AND

- [ ] Based on Content Type make fields below it conditional using https://www.contentful.com/blog/2019/09/09/customize-editorial-experience-entry-extensions/ and research on this @bronz3beard has done that I need to track down and link to [here](https://docs.google.com/document/d/1TesQqDzgz1rQNT713M8fZO-DBbLAUM7e-_5VbyAIXN0/edit?usp=sharing) :) @camposcristianeze 👆🏻 and 👇🏻  is related to the DM from @bronz3beard today. 
- [ ] Resolve and merge https://github.com/aimementoring/website/pull/223 // It simplifies parts of the Stories model that we didn't get right in the first crack. It's also a good example of why we need to be careful with our modeling as @bronz3beard is facing a challenge where this update is a breaking change to production and will require editing a bunch of posts. 
- Whats the threshold for Reports and other Content Types being their own seperate Model and not part of Posts?
