### ISSUE TITLE
Integrate Intercom

### ISSUE THREAD

**Issue by camposcristian** [aimementoring/website#7]
Following [this doc](https://docs.google.com/document/d/1hrfejgzTvc4vGsqMQ-j0XNYtKDAWmkA0Xp8J_Zl8YAk/edit) I started a test account for Intercom, the temporary credentials are:

```
user: website+intercom@aimementoring.com
pass: f!9Zbfcug3SWBYz
```

**Task List**
- [x] Integrate the [Intercom Chat](https://stackoverflow.com/questions/42382809/how-do-i-add-the-intercom-script-in-my-react-app)
- [x] Import all [FAQs](https://aimeweb-backend-production.herokuapp.com/api/faq) as articles
- [ ] Remove contact page. Redirect faq to articles
